
    create table tb_candidatos (
       cep varchar(255),
        nome varchar(255),
        id_usuario bigint not null,
        cargo_id bigint,
        primary key (id_usuario)
    );

    create table tb_cargos (
       id bigint generated by default as identity,
        nome varchar(255),
        primary key (id)
    );

    create table tb_concursos (
       id bigint generated by default as identity,
        cedente varchar(255),
        escolaridade varchar(255),
        estado varchar(255),
        local varchar(255),
        prazo timestamp,
        salario double,
        vagas integer,
        empresa_id bigint,
        primary key (id)
    );

    create table tb_empresas (
       celular varchar(11),
        cep varchar(8),
        cnpj varchar(255),
        nome varchar(100),
        nome_responsavel varchar(100),
        qtd_funcionarios integer not null,
        telefone varchar(11),
        id_usuario bigint not null,
        primary key (id_usuario)
    );

    create table tb_usuarios (
       type varchar(31) not null,
        id bigint generated by default as identity,
        data_cadastro timestamp,
        email varchar(100),
        senha varchar(100),
        tipo_usuario integer,
        primary key (id)
    );

    create table tb_vagas (
       id bigint generated by default as identity,
        expiracao timestamp,
        localizacao varchar(255),
        nome varchar(255),
        quantidade integer,
        salario double,
        tipo varchar(255),
        empresa_id bigint,
        primary key (id)
    );

    alter table tb_usuarios 
       add constraint UK_hymsg6hpnk88xrsy9kdsuhur9 unique (email);

    alter table tb_candidatos 
       add constraint FKe82hpimx51n1ahbqp881m3xub 
       foreign key (cargo_id) 
       references tb_cargos;

    alter table tb_candidatos 
       add constraint FK7ej66hactsyav2pyej6q4xjx8 
       foreign key (id_usuario) 
       references tb_usuarios;

    alter table tb_concursos 
       add constraint FK7q9friaf4kjwo6sibyejilhne 
       foreign key (empresa_id) 
       references tb_empresas;

    alter table tb_empresas 
       add constraint FK5ssb1cvj0g0njl322371i5i77 
       foreign key (id_usuario) 
       references tb_usuarios;

    alter table tb_vagas 
       add constraint FK2s7r1665spgq9ab5wgom6bl05 
       foreign key (empresa_id) 
       references tb_empresas;

    create table tb_candidatos (
       cep varchar(255),
        nome varchar(255),
        id_usuario bigint not null,
        cargo_id bigint,
        primary key (id_usuario)
    );

    create table tb_cargos (
       id bigint generated by default as identity,
        nome varchar(255),
        primary key (id)
    );

    create table tb_concursos (
       id bigint generated by default as identity,
        cedente varchar(255),
        escolaridade varchar(255),
        estado varchar(255),
        local varchar(255),
        prazo timestamp,
        salario double,
        vagas integer,
        empresa_id bigint,
        primary key (id)
    );

    create table tb_empresas (
       celular varchar(11),
        cep varchar(8),
        cnpj varchar(255),
        nome varchar(100),
        nome_responsavel varchar(100),
        qtd_funcionarios integer not null,
        telefone varchar(11),
        id_usuario bigint not null,
        primary key (id_usuario)
    );

    create table tb_usuarios (
       type varchar(31) not null,
        id bigint generated by default as identity,
        data_cadastro timestamp,
        email varchar(100),
        senha varchar(100),
        tipo_usuario integer,
        primary key (id)
    );

    create table tb_vagas (
       id bigint generated by default as identity,
        expiracao timestamp,
        localizacao varchar(255),
        nome varchar(255),
        quantidade integer,
        salario double,
        tipo varchar(255),
        empresa_id bigint,
        primary key (id)
    );

    alter table tb_usuarios 
       add constraint UK_hymsg6hpnk88xrsy9kdsuhur9 unique (email);

    alter table tb_candidatos 
       add constraint FKe82hpimx51n1ahbqp881m3xub 
       foreign key (cargo_id) 
       references tb_cargos;

    alter table tb_candidatos 
       add constraint FK7ej66hactsyav2pyej6q4xjx8 
       foreign key (id_usuario) 
       references tb_usuarios;

    alter table tb_concursos 
       add constraint FK7q9friaf4kjwo6sibyejilhne 
       foreign key (empresa_id) 
       references tb_empresas;

    alter table tb_empresas 
       add constraint FK5ssb1cvj0g0njl322371i5i77 
       foreign key (id_usuario) 
       references tb_usuarios;

    alter table tb_vagas 
       add constraint FK2s7r1665spgq9ab5wgom6bl05 
       foreign key (empresa_id) 
       references tb_empresas;
